### PR TITLE
Add border-radius style to Calendar Widget when the date is a non-working-day and selected

### PR DESCRIPTION
**Pull request by mojith**
## Checklist

- [ ] Test Coverage is 100% for the newly added code
- [ ] Storybook stories are added/updated for the changed areas
- [ ] Components standards defined [in this document](https://docs.google.com/document/d/16_Nd3VxE_lTD9pVkONQ0egn7IiwyX1pVXZjzl-V4tU8/) are followed
- [x] Code is linted properly
- [x] Developer testing is done for the affected areas
- [ ] Package version updated (not applicable to ent branch)
- [x] Changelog.md updated on possible breaking (applicable to ent branch)

### CODE REVIEW

**Comment by mojith** [comment]
Before fix:
Selection_230

After Fix:
Selection_231

**Comment by Super-Chama** [comment]
Visual change here looks not OXD compatible. This is how opensource calendar looks with selected date is non-working.

image

**Review by Super-Chama — COMMENTED** [review]
Visual change here looks not OXD compatible. This is how opensource calendar looks with selected date is non-working.

image

**Comment by mojith** [comment]
@Super-Chama This can be corrected by setting correct classes by the time we use the component
Selection_233

This is how it looks like after setting correct classes in Enterprise Product.

**Comment by mojith** [comment]
Closing the PR since the underlying issue was a different one

**Pull request closed without merging**
